@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Feb 18 17:04:10 -0800 2026
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_pipeline_behav -key {Behavioral:sim_1:Functional:tb_pipeline} -tclbatch tb_pipeline.tcl -view C:/Users/collw/Documents/School/CPE 333/otter-pipelined/Lab4.srcs/sim_1/imports/School/CPE233/Lab5/Lab4.sim/otter_tb_behav.wcfg -log simulate.log"
call xsim  tb_pipeline_behav -key {Behavioral:sim_1:Functional:tb_pipeline} -tclbatch tb_pipeline.tcl -view C:/Users/collw/Documents/School/CPE 333/otter-pipelined/Lab4.srcs/sim_1/imports/School/CPE233/Lab5/Lab4.sim/otter_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
